config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  resources :categories, except: :show
  resources :boards, except: [:destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :board,  except: :index do
    resources :tickets, only: [:new, :create, :destroy]
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :category
  has_many :comments
  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank
  validates :title, presence: true
  validates :owner, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :boards
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :board, touch: true
  validates :text, presence: true
  validates :commentator, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  PER = 10
  before_action :set_board, only: [:show, :update]

  def show
    comments_all = Comment.where(board: params[:id]).order(:updated_at)

    @owner_first_comment = Comment.where(board: params[:id]).order(:updated_at).first

    @comments = Comment
                  .where(board: params[:id]).order(:updated_at)
                  .where.not(id: @owner_first_comment.id)
                  .page(params[:page]).per(PER)
  end

  def new
    @categories = Category.all
    @board = Board.new
    @board.comments.build
  end

  def create
    @board = Board.new(board_params)
    @board.comments.each do |comment|
      comment.commentator = board_params[:owner]
    end

    respond_to do |format|
      if @board.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @board.update(board_params)
      flash[:notice] = "コメントを登録しました"
      head 201
    else
      render json:{messages: board.errors.full_messages}, status: 422
    end
  end

  private
  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:category_id, :title, :owner,
                                   comments_attributes: [
                                    :id,
                                    :text,
                                    :commentator
                                    ])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  PER = 10

  before_action :set_category, only: [:edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.page(params[:page]).per(PER)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'カテゴリーを更新しました' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'カテゴリーを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    comment.board_id = params[:board_id]

    if comment.save
      flash[:notice] = "コメントを登録しました"
      head 201
    else
      render json:{messages: comment.errors.full_messages}, status: 422
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:board_id, :text, :commentator)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER = 10

  def index
    @boards = Board.order("updated_at DESC"). page(params[:page]).per(PER)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_datetime(date, format_type)
    format = ""
    case format_type
    when :datetime then
      format = "%Y年%-m月%-d日 %-H:%M:%S"
    end
    date.strftime(format)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/_comment.html.erb
<div class="comment">
  <%= content_tag :p do %>
    <div class="no">
      <%= no %>
    </div>
    <div class="date">
      <%= format_datetime(comment.updated_at, :datetime) %>
    </div>
    <%= content_tag :p, class: "commentator" do comment.commentator end %>
  <% end %>
  <%= content_tag :p, class: "text" do comment.text end %>
</div>

app/views/boards/_form.html.erb
<% submit_btn_name = board.persisted? ? "更新" : "追加" %>

<%= form_for(board, class: "form-horizontal", role: "form") do |f| %>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, categories, :id, :name, {}, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <% if board.new_record? %>
    <%= f.fields_for(:comments, class: "form-horizontal", role: "form") do |g| %>
      <div class="form-group">
        <%= g.label :text %>
        <%= g.text_area :text, class: "form-control" %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :owner %>
    <%= f.text_field :owner, class: "form-control" %>
  </div>
  <%= f.submit submit_btn_name, class: 'btn btn-info btn-lg' %>
  <%= link_to "キャンセル", root_path, class: "btn btn-default btn-lg" %>
<% end %>

app/views/boards/new.html.erb
<div class="page-header">
  <h1>新規スレッド作成</h1>
</div>
<%= render partial: "form", locals: {categories: @categories, board: @board} %>

app/views/boards/show.html.erb
<div class="page-header">
  <h1></h1>
</div>

<div class="panel panel-primary">
  <div class="panel-heading"></div>
  <div class="panel-body">
    <h3>
      <%= link_to @board.title, board_path %>
    </h3>
    <p>更新日時：
      <%= format_datetime(@board.updated_at,:datetime) %>
    </p>
    <hr>
    <%= render partial: "comment", locals: { no: "1", comment: @owner_first_comment } %>
  </div>
</div>

<div class="board_add_comment">
  <!-- TODO: このスレッドにコメントするのアクション -->
  <button class="btn btn-success btn-block" data-toggle="modal" data-target="#createComment">
    このスレッドにコメントする
  </button>
  <div class="modal fade" id="createComment" tabindex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
          </button>
          <h4 class="modal-title" id="dialogHeader">
            コメント
          </h4>
        </div>
        <%= form_for(@board.comments.build, url:board_comments_path(@board), remote: true) do |f| %>
          <div class="modal-body">
            <div class="form-group">
              <%= f.label :text %>
              <%= f.text_area :text, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :commentator %>
              <%= f.text_field :commentator, class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              キャンセル
            </button>
            <%= f.submit "コメントを登録", class: "btn btn-primary", data: { disable_with: "送信中..." } %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>
<br>
<div id="move_to_root_btn">
  <%= link_to "トップページに戻る", root_path, class:"btn btn-default btn-block" %>
</div>
<br>
<% if @comments %>
  <%= paginate @comments %>
  <div class="panel panel-info">
    <div class="panel-heading"></div>
    <div class="panel-body">
      <% @comments.each_with_index do |comment, i| %>
        <%= render partial: "comment", locals: { no: "#{(@comments.current_page - 1) * 10 + i + 2}", comment: comment } %>
        <hr>
      <% end %>
    </div>
  </div>
  <%= paginate @comments %>
<% end %>

app/views/categories/_form.html.erb
<% btn_name = @category.persisted? ? '更新' : '追加' %>

<%= form_for(@category, class: 'form-horizontal', role: 'form') do |f| %>
  <% if @category.errors.any? %>
    <div class='alert alert-danger'>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit btn_name, class: 'btn btn-info btn-lg' %>
  <% if @category.persisted? %>
    <%= link_to '削除', category_path(@category), method: :delete, class: 'btn btn-danger btn-lg', data: { confirm: '本当に削除しますか？' } %>
  <% end %>
  <%= link_to 'キャンセル', categories_path, class: 'btn btn-default btn-lg' %>
<% end %>

app/views/categories/edit.html.erb
<div class='page-header'>
  <h1>カテゴリー編集</h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">
  <h1>カテゴリー一覧</h1>
</div>

<div class='list-group'>
  <% @categories.each do |category| %>
    <%= link_to category.name, edit_category_path(category), class:'list-group-item' %>
  <% end %>
  <%= paginate @categories %>
</div>

<%= link_to '新規追加', new_category_path, class: 'btn btn-info' %>

app/views/categories/new.html.erb
<div class="page-header">
  <h1>新規カテゴリ追加</h1>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BulletinBoard</title>
  <meta name="viewport" content="width=divice-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% if flash[:notice] %>
    <div class='alert alert-success'>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class='alert alert-danger'>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>掲示板へようこそ</h1>
</div>

<div id="create_new_board_btn">
  <%= link_to "新規スレッドを作成する", new_board_path, class: "btn btn-danger btn-lg", id: "create_new_board_btn" %>
</div>
<br>

<h3>最近更新されたスレッド</h3>
<div class='list-group'>
  <% @boards.each do |board| %>
    <%= content_tag :a, href: board_path(board), class: 'list-group-item' do %>
      <div class='list-group-item-heading'>
        <%= board.title %>
        <%= content_tag :span, board.comments.size, class: 'badge' %>
      </div>
      <p class='list-group-item-text'>
        <%= board.comments.last.text %>
      </p>
    <% end %>
  <% end %>
  <%= paginate @boards %>
</div>